### ISSUE TITLE
[MacOS] Application become unresponsive after Hot Restart.

### ISSUE THREAD

**Issue by Vovcharaa** [leanflutter/window_manager#314]
My code 
main.dart:
```dart
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await windowManager.ensureInitialized();
  WindowOptions windowOptions = const WindowOptions(
    size: Size(1200, 800),
    center: true,
    backgroundColor: Colors.transparent,
    skipTaskbar: false,
    titleBarStyle: TitleBarStyle.hidden,
  );
  windowManager.waitUntilReadyToShow(windowOptions, () async {
    await windowManager.show();
    await windowManager.focus();
  });
  runApp(const MainApp());
}
```
If I add `await` for `waitUntilReadyToShow` it actually never returns.

macos/Runner/MainFlutterWindow.swift:
```swift
import Cocoa
import FlutterMacOS
import window_manager

class MainFlutterWindow: NSWindow {
  override func awakeFromNib() {
    let flutterViewController = FlutterViewController.init()
    let windowFrame = self.frame
    self.contentViewController = flutterViewController
    self.setFrame(windowFrame, display: true)

    RegisterGeneratedPlugins(registry: flutterViewController)

    super.awakeFromNib()
  }

  override public func order(_ place: NSWindow.OrderingMode, relativeTo otherWin: Int) {
      super.order(place, relativeTo: otherWin)
      hiddenWindowAtLaunch()
  }
}
```
flutter doctor -v:
```
~ ❯ flutter doctor -v
[✓] Flutter (Channel stable, 3.7.7, on macOS 13.2.1 22D68 darwin-arm64, locale en-UA)
    • Flutter version 3.7.7 on channel stable at /Users/user/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2ad6cd72c0 (5 days ago), 2023-03-08 09:41:59 -0800
    • Engine revision 1837b5be5f
    • Dart version 2.19.4
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.76.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 111.0.5563.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by clong1995** [comment]
I had the same problem

**Comment by tgloc96** [comment]
I had the same problem

**Comment by lijy91** [comment]
Can you try running example and confirm if this issue exists? Because I can't reproduce it.

**Comment by Vovcharaa** [comment]
@lijy91 I tried my example and it indeed does not reproduce the issue. Right now, I trying to create PoC of this bug with new project. 
I tried using debugger on my project and found only that bug occurs when `size` is provided to `WindowOptions`.
But it behaves very weird. If I go through every step with debugger, `setSize` function call succeeded in `waitUntilReadyToShow`, but if I skip over this call, it just hungs.
I will update you when I create an example project where you can consistenly reproduce this issue.

**Comment by Vovcharaa** [comment]
If it would any help, these are deps in project with this issue:
```yaml
  flutter_bloc: ^8.1.2
  bloc: ^8.1.1
  intl: ^0.17.0
  equatable: ^2.0.5
  auto_route: ^6.0.5
  get_it: ^7.2.0
  animated_check: ^1.0.5
  copy_with_extension: ^5.0.2
  data_table_2: ^2.4.1
  dartx: ^1.1.0
  number_paginator: ^0.2.3
  file_selector: ^0.9.2+4
  desktop_drop: ^0.4.1
  filesize: ^2.0.1
  flutter_svg: ^2.0.4
  dotted_border: ^2.0.0+3
  blur: ^3.1.0
  octo_image: ^1.0.2
  great_list_view: ^0.2.3
  auto_updater: ^0.1.6
  realm: ^1.0.3
  flutter_web_auth_2: ^2.1.2
  cookie_jar: ^3.0.1
  device_info_plus: ^8.1.0
  dio: ^5.0.3
  dio_cookie_manager: ^2.1.4
  native_dio_adapter: ^0.1.0
  pretty_dio_logger: ^1.3.1
  font_awesome_flutter: ^10.4.0
  window_manager: ^0.3.1
  package_info_plus: ^3.0.3
  ```
